import {
  ArrowDown,
  Back,
  CaretLeft,
  CaretRight,
  Check,
  CircleCheck,
  CircleClose,
  Close,
  CollectionTag,
  CopyDocument,
  DataAnalysis,
  Delete,
  DeleteFilled,
  Document,
  Download,
  Edit,
  EditPen,
  FolderChecked,
  FolderOpened,
  FullScreen,
  InfoFilled,
  Lock,
  Loading,
  Message,
  Opportunity,
  Plus,
  Refresh,
  RefreshLeft,
  RefreshRight,
  Search,
  Share,
  Tickets,
  Tools,
  Upload,
  UploadFilled,
  UserFilled
} from '@element-plus/icons-vue'

export default {
  'el-icon-arrow-down': ArrowDown,
  'el-icon-back': Back,
  'el-icon-caret-left': CaretLeft,
  'el-icon-caret-right': CaretRight,
  'el-icon-check': Check,
  'el-icon-circle-check': CircleCheck,
  'el-icon-circle-close': CircleClose,
  'el-icon-close': Close,
  'el-icon-collection-tag': CollectionTag,
  'el-icon-data-analysis': DataAnalysis,
  'el-icon-delete': Delete,
  'el-icon-delete-solid': DeleteFilled,
  'el-icon-document': Document,
  'el-icon-document-copy': CopyDocument,
  'el-icon-download': Download,
  'el-icon-edit': Edit,
  'el-icon-edit-outline': EditPen,
  'el-icon-folder-checked': FolderChecked,
  'el-icon-folder-opened': FolderOpened,
  'el-icon-full-screen': FullScreen,
  'el-icon-info': InfoFilled,
  'el-icon-lock': Lock,
  'el-icon-loading': Loading,
  'el-icon-message': Message,
  'el-icon-plus': Plus,
  'el-icon-s-opportunity': Opportunity,
  'el-icon-refresh': Refresh,
  'el-icon-refresh-left': RefreshLeft,
  'el-icon-refresh-right': RefreshRight,
  'el-icon-s-check': UserFilled,
  'el-icon-search': Search,
  'el-icon-share': Share,
  'el-icon-s-tools': Tools,
  'el-icon-tickets': Tickets,
  'el-icon-upload': Upload,
  'el-icon-upload2': UploadFilled,
  'el-icon-user-solid': UserFilled
}
